### ISSUE TITLE
Некорректное появление в роли антагониста.

### ISSUE THREAD

**Issue by Ristty** [WalkmanNik/Osiris-SS13#21]
### Для гостов есть возможность в середине раунда стать генокрадом.

При этом появление происходит в теле игрока, который умер и так же является гостом.
Проблема в том, что регенерируется всё, за исключением лица. Вследствие этого нету возможности общаться и корректно взаимодействовать с персонажами.

Воспроизведение:
1. Быть гостом (не обязательно с начала раунда)
2. Принять предложение стать генокрадом.
3. Появление в теле.

Прошу заметить, что остальные функции доступны, отсутствует только возможность говорить.
Так же есть возможность потреблять пищу.
Смена языка не помогает, персонаж молчит, какой бы язык не был по умолчанию.

**Comment by WalkmanNik** [comment]
Этот баг появлялся единично? Были ли произведены повторные проверки?

**Comment by DarkLevelSS13** [comment]
Как я помню, вчера один из игроков жаловался, что такое произошёл два раза. Тем более. Я сам был генкой в тот раунд, и видел, как тех кого я убил и даже, так сказать, "поработил душу", вставали, не могли говорить, и ходили мочить экипаж... Это как странно, как минимум.

**Comment by Ristty** [comment]
> Этот баг появлялся единично? Были ли произведены повторные проверки?

Два раза был генкой, два раза молчал и ничего не мог сказать

**Comment by IvanDonFon** [comment]
+. Такое-же было. Я ни то, что заспавнился без лица и не мог говорить - мои способности не работали, ибо нужен был один геном. А без способностей и голоса я не могу выбраться из гроба,в котором я был

**Comment by FreimK** [comment]
Это фича.
Неумение говорить и сломанное лицо - штраф за возрождение в качестве антага в середине раунда. Лечится, насколько мне известно, поглощением генома. Насчет последнего не уверен, нужно проверить.

**Comment by Ristty** [comment]
Это фича, увы.
Issue закрывается.
