### ISSUE TITLE
Чудо-FOV

### ISSUE THREAD

**Issue by FreimK** [WalkmanNik/Osiris-SS13#34]
## Описание
От нового FOV'a больше проблем, чем пользы. Из плюсов можно отметить:
- В игре потенциально появляется стелс. Наверняка отыгрыш Солида Снейка принесет некоторым море удовольствия.
- Играет на **РеАлИзМ**. FOV так или иначе заставляет больше верить в происходящее.

Это единственные плюсы, которые я смог для себя выделить. Перейдем к минусам.
- FOV очень мешает в драках. При толчках персонаж поворачивается в противоположную сторону, спрайт оппонента пропадает и персонаж не может его ударить. Ему либо приходится тратить на это еще один клик (чтобы повернуться обратно), либо зажимать С (что неудобно, плюс это требует активированных хоткеев, а не все их используют), либо спамить кнопку движения по направлению к противнику (что также неудобно). Особенно сильно этот пункт мешает во время драк с тараканами. Сквозь них можно пройти, спрайт персонажа, насколько я знаю, находится **над** тараканами, ходят они толпой. При попытке повернуть персонажа обратно кнопкой движения персонаж залезает в толпу.
- Если верить некоторым Мудрейшим из Дискордии, из-за FOV'a игра лагает. Если это действительно так, то робуст становится еще более невыносимым.
- Сомнительная реализация стелса. В отличие от боевки тут нажатие лишних кнопок очень несущественное действие. Игроки иногда от нехер делать просто крутятся на месте. "Звуки" от шагов видны. К тому же лично я ни разу не наблюдал игровую ситуацию, где использовался стелс.
- К предыдущему пункту: HUD-очки позволяют запросто узнать, кто за тобой находится. Портит стелс и атмосферу.

## Возможные решения.
- Выпилить FOV и играть как раньше.
- Пункт 1 из минусов можно исправить, если при толчке персонаж не будет поворачивать в противоположную сторону. Фикс 4 пункта очевиден.

**Comment by WalkmanNik** [comment]
Аргументы весомые.
Выпиливаем.

**Comment by FreimK** [comment]
Уже давно выпилено.
