### ISSUE TITLE
Революционер может говорить в имплант после смерти

### ISSUE THREAD

**Issue by IvanDonFon** [WalkmanNik/Osiris-SS13#40]
### Проблема
Если умереть, будучи ревом - Вы всё-равно сможете говорить в Ваш имплант

### Воспроизведение
* Станьте ревом
* Умрите(Это не призыв к суициду)
* Нажмите кнопку Re-Enter Corpse
* Попробуйте что-то сказать через имплант - и ВуАля! Вы говорите!

**Comment by FreimK** [comment]
@WalkmanNik 
Закрывай.
